import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'


const roboto = Inter({subsets:['latin']})

export const metadata: Metadata = {
  title: 'Floodgen',
  description: 'Generated by create next app',
  icons:"/app/fg_logo_white_sm.png"
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
      <link
          href="https://api.mapbox.com/mapbox-gl-js/v2.15.0/mapbox-gl.css"
          rel="stylesheet"
        />
      </head>
      <body className={roboto.className} suppressHydrationWarning={true}>{children}</body>
    </html>
  )
}
