import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

import Script from 'next/script'


const roboto = Inter({subsets:['latin']})

export const metadata: Metadata = {
  title: 'FloodGen',
  description: 'Generated by create next app',
  icons:"/app/fg_logo_white_sm.png"
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
      <Script async src="https://www.googletagmanager.com/gtag/js?id=G-CCN79CWRX0" />
        <Script id="google-analytics">
          {`
          window.dataLayer = window.dataLayer || [];
          function gtag(){dataLayer.push(arguments);}
          gtag('js', new Date());
          gtag('config', 'G-CCN79CWRX0');
          `}
        </Script>
      <link
          href="https://api.mapbox.com/mapbox-gl-js/v2.15.0/mapbox-gl.css"
          rel="stylesheet"
        />
      </head>
      <body className={roboto.className} suppressHydrationWarning={true}>{children}</body>
    </html>
  )
}

